# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Check if terminal has color support
# (There are other terminals with color support but many are listed as simply "xterm")
case "$TERM" in
    xterm*|rxvt*)
        color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# If using color, set different colors depending on HOSTNAME
if [ "$color_prompt" = yes ]; then
  if [[ $HOSTNAME == *uppmax* ]]; then  # Red
    PS1='${debian_chroot:+($debian_chroot)}[\[\033[0;31m\]\u@\h\[\033[00m\]:${ENV}\[\033[01;34m\]\W\[\033[00m\]]\$ '
  elif [[ $HOSTNAME == trio* ]]; then   # Purple
    PS1='${debian_chroot:+($debian_chroot)}[\[\033[0;35m\]\u@\h\[\033[00m\]:${ENV}:\[\033[01;34m\]\W\[\033[00m\]]\$ '
  elif [[ $HOSTNAME == *amDi* ]];then  # Blue
    PS1='${debian_chroot:+($debian_chroot)}[\[\e[34m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\W\[\e[00m\]]\$ '
  elif [[ $HOSTNAME == YOGH* ]]; then # Yellow
    PS1='${debian_chroot:+($debian_chroot)}[\[\e[33m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\W\[\e[00m\]]\$ '
  else  # Default: green
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
  fi
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\W\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \W\a\]$PS1"
#    ;;
#*)
#    ;;
#esac

# Function definition.
# Useful tools which are too complicated to be cleanly added as aliases
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# Alias definitions (may bulid upon functions)
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Prevent weird behaviour of bash excaping '$' when tab-completing
shopt -s direxpand

#Set environment variables:
export AFS2=$HOME/Models/stable/flx_wrf2/AFS2
export WRF=$HOME/local/lib/ncarg/nclscripts/wrf
#export NETCDF=$HOME/local
export NCARG_ROOT=/opt
export NCARG_COLORMAP_PATH=$HOME/ncl/colormaps
#export NCARG_COLORMAPS=$HOME/ncl/colormaps:$NCARG_ROOT/lib/ncarg/colormaps
export MIDAS_DATA_DIR=/mnt/DATA/obs/midas
export WRF_MIDAS_ROOT=$HOME/programming/git/compare_wrf_midas
export PYWRFPATH=.:$HOME/programming/git/external/pyWRF
export PYTHONPATH=.:$HOME/python:/opt/lib/python2.7/:usr/local/lib/python:$PYWRFPATH
export PYTHONSTARTUP=$HOME/.python_startup
export MATLABPATH=.:$HOME/matlab/pilt_functions:$HOME/matlab/googleearth  # Will automatically append ~/matlab if it exists

# The following was set to make OPT-installed packages work (mainly NCO)
export PATH=/opt/bin:$PATH
export LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH
export HDF5_DISABLE_VERSION_CHECK=1 # The HDF5 build ALWAYS fails on this!
