# BASH aliases
#
# Some of these aliases require functions defined in bash_functions 
# Therefore, bash_functions should be sourced before bash_aliases!

# Application launch
alias go='gnome-open'
alias octave='octave --no-gui'
# alias matlab="matlab -nodesktop -nosplash" #using wrapper $HOME/bin/matlab instead

# Color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias diff=colordiff_safe # Defined in .bash_functions

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Terminal Display/Listing
alias l='ls -CF'
alias sl='ls -s --block-size=MB'    # Size-list
alias less='less -i'                # Case insensitive searches

# some more ls aliases (from Ubuntu .bashrc)
#alias ll='ls -alF'
#alias la='ls -A'
#alias l='ls -CF'

# Navigation
alias cdwork='cd $HOME/Documents/Jobb/phd'

# Notification
#   Run alert like this:
#     sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# SLURM
alias squeue='squeue -u$USER -o "%.7i %.9P %.8j %.8u %.2t %.10M %.6D %16S %R"'
alias watch-queue="watch '"'squeue -u$USER -o "%.7i %.9P %.8j %.8u %.2t %.10M %.6D %16S %R"'"'"

# SSH
alias ssh="ssh -X" # Use X-forwarding by default.
