"Color Scheme
  colorscheme zenburn

"Jump to last position when re-opening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"Disable blinking cursor
  set guicursor+=a:blinkon0

"Indentation settings
  set tabstop=2
  set expandtab
  set shiftwidth=2
  set smarttab autoindent

"File type settings
  filetype plugin on
  filetype indent on

"
" Filetype specific
"


" Octave Syntax
"    augroup filetypedetect
"        au! BufRead,BufNewFile *.m,*.oct setfiletype octave
"    augroup END

" matchit required for matlab stuff (improves the % command) %included by
" default?
  source $HOME/.vim/plugin/matchit.vim


" Matlab
  let mlint_hover = 0  
" source $VIMRUNTIME/macros/matchit.vim
" source $HOME/.vim/macros/matchit.vim
" autocmd BufEnter *.m    compiler mlint
" au Bufread,BufNewFile *.m set filetype=matlab
" au! Syntax newlang source $VIM/matlab.vim

" NCL Syntax
  au Bufread,BufNewFile *.ncl set filetype=ncl
  au! Syntax newlang source $VIM/ncl.vim

" NCL autocompletion
  set complete-=k complete+=k 
  set wildmode=list:full
  set wildmenu
  au BufRead,BufNewFile *.ncl set dictionary=~/.vim/dictionary/ncl.dic

