"Color Scheme
"  colorscheme zenburn
"  colorscheme molokai
"  colorscheme evolution
"  colorscheme molokai_dark
  colorscheme antares

"Jump to last position when re-opening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"Turn on line-numbering by default:
  set number

"Disable blinking cursor
  set guicursor+=a:blinkon0

" Default indentation settings
  set expandtab
  set tabstop=2
  set softtabstop=2
  set shiftwidth=2
  set smarttab autoindent

"File type settings
  filetype plugin on
  filetype indent on

"Mouse settings
  set mouse=c   "Enforce command-line mouse settings even in gvim
"
" Filetype specific (TODO: move to filetype specific config files)
"

" NCL Syntax
  au Bufread,BufNewFile *.ncl set filetype=ncl
  au! Syntax newlang source $VIM/ncl.vim

" Python
  au BufRead,BufNewFile *.py set filetype=python

" Shell (sh)
  let g:sh_fold_enabled = 1
  
" Vimlatex-suite
  set grepprg=grep\ -nH\ $*
  let g:tex_flavor='latex'
  "let g:Tex_AutoFolding = 1

